clinica/apps/profesionalservicio/urls.py
from django.urls import path
from .views import ServicioProfesionalListView, VincularServicioView

app_name = 'profesionalservicio'

urlpatterns = [
    path('servicios_profesional/<int:profesional_id>/', ServicioProfesionalListView.as_view(), name='lista_servicios_profesionales'),

    path('vincular_servicio/<int:profesional_id>/', VincularServicioView.as_view(), name='vincular_servicio'),
    
    ]

clinica/apps/turno/urls.py
from django.urls import path
from .views import SeleccionarFechaView, SeleccionarHorarioView, ConfirmarTurnoView, TurnoConfirmadoView, GenerarFechasView

app_name = 'turno'

urlpatterns = [
    path('seleccionar_fecha/<int:servicio_id>/<int:profesionalservicio_id>/', SeleccionarFechaView.as_view(), name='seleccionar_fecha'),
    path('seleccionar_horario/<int:fecha_id>/<int:profesionalservicio_id>/', SeleccionarHorarioView.as_view(), name='seleccionar_horario'),
    path('confirmar_turno/<int:fecha_id>/<int:horario_id>/<int:profesionalservicio_id>/', ConfirmarTurnoView.as_view(), name='confirmar_turno'),
    path('turno_confirmado/', TurnoConfirmadoView.as_view(), name='turno_confirmado'),
    path('generar_fechas/', GenerarFechasView.as_view(), name='generar_fechas'),
]

clinica/clinica/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import BaseView

app_name = 'clinica'

urlpatterns = [
 
    path('admin/', admin.site.urls),

    path('', BaseView.as_view(), name='base' ),

    path('profesional/', include('apps.profesional.urls')),

    path('servicio/', include('apps.servicio.urls')),

    path('profesionalservicio/', include('apps.profesionalservicio.urls')),

    path('accounts/', include('apps.accounts.urls')),

    path('turno/', include('apps.turno.urls')),

]

clinica/apps/profesionalservicio/models.py
from django.db import models
from apps.profesional.models import Profesional
from apps.servicio.models import Servicio
# Create your models here.

class ProfesionalServicio(models.Model):
    profesional = models.ForeignKey(Profesional, on_delete = models.CASCADE)
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE)
    fecha_borrado = models.DateField(null= True)
    # Otros campos o métodos relacionados a la relación Profesional-Servicio

clinica/apps/profesionalservicio/forms.py
from django import forms
from apps.servicio.models import Servicio

class VincularServicioForm(forms.Form):
    servicio = forms.ModelChoiceField(queryset=Servicio.objects.filter(is_deleted=False))

clinica/apps/profesionalservicio/views.py
# Create your views here.
#from django.shortcuts import render
from typing import Any
from django.db.models.query import QuerySet
from django.db.models import Q
from .models import ProfesionalServicio
from django.views.generic import ListView
from apps.profesional.models import Profesional
from apps.servicio.models import Servicio
from django.shortcuts import redirect, render
from .forms import VincularServicioForm
from django.urls import reverse_lazy
from django.views.generic import FormView
from django.contrib import messages


class ServicioProfesionalListView(ListView):
    template_name = 'lista_servicios_profesionales.html'
    context_object_name = 'profesional_servicios'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profesional_id = self.kwargs['profesional_id']
        profesional = Profesional.objects.get(id=profesional_id)
        context['profesional'] = profesional
        context['vincular_url'] = reverse_lazy('profesionalservicio:vincular_servicio', kwargs={'profesional_id': profesional_id})
        return context

    def get_queryset(self):
        profesional_id = self.kwargs['profesional_id']
        return ProfesionalServicio.objects.filter(
            Q(profesional_id=profesional_id) & Q(servicio__is_deleted=False)
        )




class VincularServicioView(FormView):
    template_name = 'vincular_servicio.html'
    form_class = VincularServicioForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profesional_id = self.kwargs['profesional_id']
        profesional = Profesional.objects.get(id=profesional_id)
        context['profesional'] = profesional
        return context

    def form_valid(self, form):
        profesional_id = self.kwargs['profesional_id']
        profesional = Profesional.objects.get(id=profesional_id)
        servicio = form.cleaned_data['servicio']

        # Verificar si el servicio ya está vinculado al profesional
        if ProfesionalServicio.objects.filter(profesional=profesional, servicio=servicio).exists():
            messages.error(self.request, 'Este servicio ya está vinculado al profesional.')
            return redirect('profesionalservicio:vincular_servicio', profesional_id=profesional_id)

        # Crear el objeto ProfesionalServicio
        ProfesionalServicio.objects.create(profesional=profesional, servicio=servicio)
        return redirect('profesionalservicio:lista_servicios_profesionales', profesional_id=profesional_id)

clinica/apps/profesionalservicio/templates/lista_servicios_profesionales.html
{% extends 'base.html' %}

{% block content %}
  <h1>Servicios del profesional</h1>

  {% if profesional_servicios %}
    <ul>
      {% for ps in profesional_servicios %}
        <li>
          <a href="{% url 'turno:seleccionar_fecha' servicio_id=ps.servicio.id profesionalservicio_id=ps.id %}">
            {{ ps.servicio.nombre }} - {{ ps.servicio.precio }}
          </a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No hay servicios disponibles</p>
  {% endif %}

  {% if profesional_servicios %}
    <a class="profesional-boton" href="{{ vincular_url }}">Vincular nuevo servicio</a>
  {% else %}
    <a class="profesional-boton" href="{{ vincular_url }}">Vincular nuevo servicio</a>
  {% endif %}
{% endblock %}

clinica/apps/profesionalservicio/templates/vincular_servicio.html
{% extends 'base.html' %}

{% block title %}Vincular nuevo servicio{% endblock %}

{% block content %}
  <h1>Vincular nuevo servicio</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="borrar" type="submit">Guardar</button>
  </form>
  
  {% for message in messages %}
    <div class="alert alert-danger">
      {{ message }}
    </div>
  {% endfor %}
{% endblock %}