clinica/apps/servicio/urls.py
from django.urls import path
from .views import ListaServiciosView, CrearServicioView, ServicioDeleteView, ServicioActivarView, ServicioBorradosView, ProfesionalesDisponiblesView

app_name = 'servicio'

urlpatterns= [
    path('lista/', ListaServiciosView.as_view(), name = 'lista_servicios'),
    path('crear/', CrearServicioView.as_view(), name='crear_servicio'),
    path('borrar/<int:pk>/', ServicioDeleteView.as_view(), name='borrar_servicio'),
    path('activar/<int:pk>/',ServicioActivarView.as_view(), name='activar_servicio' ),
    path('borrados/', ServicioBorradosView.as_view(), name='servicios_borrados'),
    path('profesionales_disponibles/<int:servicio_id>/', ProfesionalesDisponiblesView.as_view(), name='profesionales_disponibles'),
]




clinica/clinica/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import BaseView

app_name = 'clinica'

urlpatterns = [
 
    path('admin/', admin.site.urls),

    path('', BaseView.as_view(), name='base' ),

    path('profesional/', include('apps.profesional.urls')),

    path('servicio/', include('apps.servicio.urls')),

    path('profesionalservicio/', include('apps.profesionalservicio.urls')),

    path('accounts/', include('apps.accounts.urls')),

    path('turno/', include('apps.turno.urls')),

]

clinica/apps/servicio/models.py
from django.db import models
from datetime import timedelta

# Create your models here.

class Servicio(models.Model):
    nombre = models.CharField(max_length=255)
    precio = models.FloatField()
    duracion = models.DurationField(default = timedelta(minutes=30))
    is_deleted = models.BooleanField(default=False)


    def __str__(self):
        return self.nombre
    

    def delete(self):
        self.is_deleted = True
        self.save()

# agregar agenta y usuario como aplicacion
# agenda se va a vincular a los turnos, los turnos se tienen que chekear una agenda, y esta agenda le va a pertenecer
#a un profesional

clinica/apps/servicio/forms.py
from django import forms
from .models import Servicio

class ServicioForm(forms.ModelForm):
    class Meta:
        model = Servicio
        fields = ['nombre', 'precio', 'duracion']


clinica/apps/servicio/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render,redirect
from django.views import View
from django.views.generic import DeleteView, ListView
from django.urls import reverse_lazy
from .forms import ServicioForm
from .models import Servicio
from apps.profesionalservicio.models import ProfesionalServicio

# Create your views here.


# def lista_servicios(request):
#     servicios = Servicio.objects.filter(is_deleted=False)
#     context = {'servicios': servicios}
#     return render(request, 'Servicios.html', context)


class ListaServiciosView(View):
    def get(self, request):
        servicios = Servicio.objects.filter(is_deleted=False)
        context = {'servicios':servicios}
        return render(request, 'Servicios.html', context)
    

class CrearServicioView(View):
    def get(self, request):
        form = ServicioForm()
        context = {'form':form}
        return render(request, 'crear_servicio.html', context)
    
    def post(self, request):
        form = ServicioForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('servicio:lista_servicios')
        context = {'form': form}
        return render(request, 'crear_servicio.html', context)
    




class ServicioDeleteView(DeleteView):
    def post(self, request, pk):
        servicio = Servicio.objects.get(pk=pk)
        servicio.delete()
        return redirect('servicio:lista_servicios')


class ServicioBorradosView(ListView):
    model = Servicio
    template_name = 'servicios_borrados.html'
    context_object_name = 'servicios'

    def get_queryset(self):
        return Servicio.objects.filter(is_deleted=True)
    
class ServicioActivarView(View):
    def post(self, request, pk):
        servicio = Servicio.objects.get(pk=pk)
        servicio.is_deleted = False
        servicio.save()
        return redirect('servicio:lista_servicios')
    

class ProfesionalesDisponiblesView(View):
    template_name = 'profesional_disponibles.html'

    def get(self, request, servicio_id):
        servicio = Servicio.objects.get(pk=servicio_id)
        profesionales_disponibles = servicio.profesionalservicio_set.all()
        context = {
            'servicio': servicio,
            'profesionales_disponibles': profesionales_disponibles
        }
        return render(request, self.template_name, context)

clinica/apps/servicio/templates/crear_servicio.html
{% extends 'base.html' %}

{% block title %} Crear Servicio {% endblock %}

{% block content %}
    <h1> Crear Servicio</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="borrar" type="sumbit"> Guardar </button>
    </form>

{% endblock %}

clinica/apps/servicio/templates/profesional_disponibles.html
{% extends 'base.html' %}

{% block title %}Profesionales disponibles para {{ servicio.nombre }}{% endblock %}

{% block content %}
  <h1>Profesionales disponibles para {{ servicio.nombre }}</h1>
  {% if profesionales_disponibles %}
    <ul>
      {% for ps in profesionales_disponibles %}
        <li>{{ ps.profesional.nombre }} {{ ps.profesional.apellido }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No hay profesionales disponibles</p>
  {% endif %}
{% endblock %}

clinica/apps/servicio/templates/servicios.html
{% extends 'base.html' %}

{% block title %}Clinica{% endblock %}

{% block content %}
    <h1> Servicios</h1>
    <ul>
        {% for servicio in servicios %}
            {% if not servicio.is_deleted %}
                <li>
                    <a href="{% url 'servicio:profesionales_disponibles' servicio.id %}">
                        {{ servicio.nombre }} - ${{ servicio.precio }}
                    </a>
                </li>
                <form method="post" action="{% url 'servicio:borrar_servicio' servicio.id %}">
                    {% csrf_token %}
                    <button class="borrar" type="submit">Borrar</button>
                </form>
            {% endif %}
        {% endfor %}
    </ul>
    <a class="profesional-boton" href="{% url 'servicio:crear_servicio' %}">Nuevo Servicio</a>
    <a class="profesional-boton" href="{% url 'servicio:servicios_borrados' %}">Reactivar Servicio</a>
{% endblock %}

clinica/apps/servicio/templates/servicios_borrados.html
{% extends 'base.html' %}


{% block content %}
  <h1>Servicios Borrados</h1>
  {% if servicios %}
    <ul>
      {% for servicio in servicios %}
        <li>{{ servicio.nombre }} - ${{ servicio.precio }}</li>
        <form action="{% url 'servicio:activar_servicio' servicio.id %}" method="post">
          {% csrf_token %}
          <button class="borrar" type="submit">Activar</button>
        </form>
      {% endfor %}
    </ul>
  {% else %}
    <p>No hay servicios borrados</p>
  {% endif %}
{% endblock %}