clinica/apps/profesional/urls.py
from django.urls import path
from .views import ProfesionalesListView, ProfesionalCreateView, ProfesionalDeleteView, ProfesionalesActivarView, ProfesionalesBorradosView

app_name = 'profesional'

urlpatterns= [
    path('lista/', ProfesionalesListView.as_view(), name = 'lista_profesionales'),

    path('crear/', ProfesionalCreateView.as_view(), name='crear_profesional'),

    path('borrar/<int:pk>/', ProfesionalDeleteView.as_view(), name='borrar_profesional'),

    path('activar/<int:pk>/', ProfesionalesActivarView.as_view(), name='activar_profesional'),

    path('borrados/', ProfesionalesBorradosView.as_view(), name='profesionales_borrados'),

]

clinica/apps/profesionalservicio/urls.py
from django.urls import path
from .views import ServicioProfesionalListView, VincularServicioView

app_name = 'profesionalservicio'

urlpatterns = [
    path('servicios_profesional/<int:profesional_id>/', ServicioProfesionalListView.as_view(), name='lista_servicios_profesionales'),

    path('vincular_servicio/<int:profesional_id>/', VincularServicioView.as_view(), name='vincular_servicio'),
    
    ]

clinica/clinica/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import BaseView

app_name = 'clinica'

urlpatterns = [
 
    path('admin/', admin.site.urls),

    path('', BaseView.as_view(), name='base' ),

    path('profesional/', include('apps.profesional.urls')),

    path('servicio/', include('apps.servicio.urls')),

    path('profesionalservicio/', include('apps.profesionalservicio.urls')),

    path('accounts/', include('apps.accounts.urls')),

    path('turno/', include('apps.turno.urls')),

]

clinica/apps/profesional/models.py
from django.db import models
from apps.servicio.models import Servicio

# Create your models here.

class Profesional(models.Model):
    nombre = models.CharField(max_length=255)
    apellido = models.CharField(max_length=255)
    email = models.EmailField(blank=False, null=False)
    is_deleted = models.BooleanField(default=False)


    def delete(self):
        self.is_deleted = True
        self.save()



clinica/apps/profesional/forms.py
from django import forms
from .models import Profesional

class ProfesionalForm(forms.ModelForm):
    class Meta:
        model = Profesional
        fields = ['nombre', 'apellido', 'email']
        widgets = {
            'email': forms.EmailInput(attrs={'placeholder': 'ejemplo@ejemplo.com.ar'}),
        }

clinica/apps/profesional/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.views.generic import ListView, CreateView, View, DeleteView
from django.shortcuts import get_object_or_404, redirect
from .models import Profesional
from .forms import ProfesionalForm
from django.urls import reverse_lazy



# Create your views here.

class ProfesionalesListView(ListView):
    template_name = 'lista_profesionales.html'
    context_object_name = 'profesionales'
    queryset = Profesional.objects.all()

class ProfesionalCreateView(CreateView):
    model = Profesional
    form_class = ProfesionalForm 
    template_name = 'crear_profesional.html'
    success_url = reverse_lazy('profesional:lista_profesionales')


class ProfesionalDeleteView(DeleteView):
    def post(self, request, pk):
        profesional = Profesional.objects.get(pk=pk)
        profesional.delete()
        return redirect('profesional:lista_profesionales')




class ProfesionalesBorradosView(ListView):
    model = Profesional
    template_name = 'profesionales_borrados.html'
    context_object_name = 'profesionales'

    def get_queryset(self):
        return Profesional.objects.filter(is_deleted=True)
    
class ProfesionalesActivarView(View):
    def post(self, request, pk):
        profesional = Profesional.objects.get(pk=pk)
        profesional.is_deleted = False
        profesional.save()
        return redirect('profesional:lista_profesionales')

clinica/apps/profesional/templates/borrar_profesional.html
{% extends 'base.html' %}

{% block content %}
  <h1>Borrar Profesional</h1>
  <form method="post" action="{% url 'profesional:borrar_profesional' profesional.id %}">
    {% csrf_token %}
    <p>¿Estás seguro de que deseas borrar al profesional "{{ profesional.nombre }} {{ profesional.apellido }}"?</p>
    <button class="borrar" type="submit">Borrar</button>
  </form>
{% endblock %}

clinica/apps/profesional/templates/crear_profesional.html
{% extends 'base.html' %}

{% block content %}
  <h1>Crear Profesional</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="borrar" type="submit">Crear</button>
  </form>
{% endblock %}

clinica/apps/profesional/templates/lista_profesionales.html
{% extends 'base.html' %}

{% block title %}Clinica{% endblock %}

{% block content %}

{% if profesionales %}
  <h1>Profesionales Disponibles</h1>
  <p>Seleccione un Profesional</p>
  <ul>
    {% for profesional in profesionales %}
      {% if not profesional.is_deleted %}
        <li><a href="{% url 'profesionalservicio:lista_servicios_profesionales' profesional.id %}">{{ profesional.nombre }} {{ profesional.apellido }}</a></li>
        <form method="post" action="{% url 'profesional:borrar_profesional' profesional.id%}">
            {%csrf_token%}
            <button class="borrar" type="sumbit">borrar</button>
        </form>
      {% else %}
        <p>No hay profesionales</p>
      {% endif %}
    {% endfor %}
  </ul>
{% else %}
  <p>No hay profesionales</p>
{% endif %}

<a class="profesional-boton" href="{% url 'profesional:crear_profesional' %}"> Nuevo Profesional</a>
<a class="profesional-boton" href="{% url 'profesional:profesionales_borrados' %}">Reactivar Profesional</a>

{% endblock %}

clinica/apps/profesional/templates/profesionales_borrados.html
{% extends 'base.html' %}


{% block content %}
  <h1>Profesionales dados de baja</h1>
  {% if profesionales %}
    <ul>
      {% for profesional in profesionales %}
        <li>{{ profesional.nombre }} {{ profesional.apellido }}</li>
        <form action="{% url 'profesional:activar_profesional' profesional.id %}" method="post">
          {% csrf_token %}
          <button class="borrar" type="submit">Activar</button>
        </form>
      {% endfor %}
    </ul>
  {% else %}
    <p>No hay profesionales borrados</p>
  {% endif %}
{% endblock %}