clinica/apps/turno/urls.py
from django.urls import path
from .views import SeleccionarFechaView, SeleccionarHorarioView, ConfirmarTurnoView, TurnoConfirmadoView, GenerarFechasView

app_name = 'turno'

urlpatterns = [
    path('seleccionar_fecha/<int:servicio_id>/<int:profesionalservicio_id>/', SeleccionarFechaView.as_view(), name='seleccionar_fecha'),
    path('seleccionar_horario/<int:fecha_id>/<int:profesionalservicio_id>/', SeleccionarHorarioView.as_view(), name='seleccionar_horario'),
    path('confirmar_turno/<int:fecha_id>/<int:horario_id>/<int:profesionalservicio_id>/', ConfirmarTurnoView.as_view(), name='confirmar_turno'),
    path('turno_confirmado/', TurnoConfirmadoView.as_view(), name='turno_confirmado'),
    path('generar_fechas/', GenerarFechasView.as_view(), name='generar_fechas'),
]

clinica/clinica/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import BaseView

app_name = 'clinica'

urlpatterns = [
 
    path('admin/', admin.site.urls),

    path('', BaseView.as_view(), name='base' ),

    path('profesional/', include('apps.profesional.urls')),

    path('servicio/', include('apps.servicio.urls')),

    path('profesionalservicio/', include('apps.profesionalservicio.urls')),

    path('accounts/', include('apps.accounts.urls')),

    path('turno/', include('apps.turno.urls')),

]

clinica/apps/turno/models.py
from django.db import models
from datetime import date, timedelta
from apps.servicio.models import Servicio
from apps.profesionalservicio.models import ProfesionalServicio
# Create your models here.


class Fecha(models.Model):
    fecha = models.DateField()
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE)

    @classmethod
    def generar_fechas_mes_corriente(cls):
        today = date.today()
        first_day = today.replace(day=1)
        next_month = (first_day + timedelta(days=32)).replace(day=1)
        servicios = Servicio.objects.all()  # Obtener todos los servicios disponibles

        fechas = []
        for servicio in servicios:
            current_day = first_day
            while current_day < next_month:
                fechas.append(cls(fecha=current_day, servicio=servicio))
                current_day += timedelta(days=1)

        cls.objects.bulk_create(fechas)




class Horario(models.Model):
    horario = models.TimeField()


class Turno(models.Model):
    profesional_servicio = models.ForeignKey(ProfesionalServicio, on_delete= models.CASCADE)
    fecha = models.ForeignKey(Fecha, on_delete=models.CASCADE)
    horario = models.ForeignKey(Horario, on_delete=models.CASCADE)

clinica/apps/turno/views.py
from django.shortcuts import render
from django.views import View
from .models import Fecha, Turno, Horario
from apps.profesionalservicio.models import ProfesionalServicio
from django.core.mail import send_mail, EmailMessage
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from apps.accounts.models import CustomUser
from datetime import date

class GenerarFechasView(View):
    def get(self, request):
        if Fecha.objects.exists():
            fechas_generadas = True
        else:
            Fecha.generar_fechas_mes_corriente()
            fechas_generadas = True

        mensaje_exito = "Las fechas se han generado exitosamente."
        return render(request, 'exito.html', {'mensaje': mensaje_exito, 'fechas_generadas': fechas_generadas})
class SeleccionarFechaView(View):
    def get(self, request, servicio_id, profesionalservicio_id):
        profesionalservicio = ProfesionalServicio.objects.get(id=profesionalservicio_id)
        today = date.today()
        fechas = Fecha.objects.filter(servicio_id=servicio_id, fecha__gte=today)
        return render(request, 'seleccionar_fecha.html', {'fechas': fechas, 'servicio_id': servicio_id, 'profesionalservicio': profesionalservicio})

class SeleccionarHorarioView(View):
    def get(self, request, fecha_id, profesionalservicio_id):
        fecha = Fecha.objects.get(id=fecha_id)
        horarios_ocupados_fecha = Turno.objects.filter(fecha=fecha).values('horario')
        horarios_disponibles = Horario.objects.exclude(id__in=horarios_ocupados_fecha)
        profesionalservicio = ProfesionalServicio.objects.get(id=profesionalservicio_id)
        return render(request, 'seleccionar_horario.html', {'fecha': fecha, 'horarios': horarios_disponibles, 'profesionalservicio': profesionalservicio})


class ConfirmarTurnoView(View):
    def get(self, request, fecha_id, horario_id, profesionalservicio_id):
        fecha = Fecha.objects.get(id=fecha_id)
        horario = Horario.objects.get(id=horario_id)
        profesionalservicio = ProfesionalServicio.objects.get(id=profesionalservicio_id)
        return render(request, 'confirmar_turno.html', {'fecha': fecha, 'horario': horario, 'profesionalservicio': profesionalservicio})

    def post(self, request, fecha_id, horario_id, profesionalservicio_id):
        fecha = Fecha.objects.get(id=fecha_id)
        horario = Horario.objects.get(id=horario_id)
        profesionalservicio = ProfesionalServicio.objects.get(id=profesionalservicio_id)

        # Renderizar el template de confirmación del turno con los datos del turno
        return render(request, 'confirmar_turno.html', {'fecha': fecha, 'horario': horario, 'profesionalservicio': profesionalservicio})
    


class TurnoConfirmadoView(View):
    @method_decorator(login_required(login_url='accounts:login'))
    def post(self, request):
        fecha_id = request.POST.get('fecha_id')
        horario_id = request.POST.get('horario_id')
        profesionalservicio_id = request.POST.get('profesionalservicio_id')

        # Obtener los objetos de turno confirmado
        fecha = Fecha.objects.get(id=fecha_id)
        horario = Horario.objects.get(id=horario_id)
        profesionalservicio = ProfesionalServicio.objects.get(id=profesionalservicio_id)

        # Guardar los datos del turno en la base de datos
        turno = Turno.objects.create(fecha=fecha, horario=horario, profesional_servicio=profesionalservicio)

       # Obtener el correo electrónico del usuario desde la sesión
        user_email = request.user.email
        print(user_email)
        # Enviar correo electrónico de confirmación al usuario
        subject = 'Confirmación de turno'
        message = f'Tu turno ha sido confirmado exitosamente.\n\n' \
                  f'Fecha: {fecha.fecha}\n' \
                  f'Horario: {horario.horario}\n' \
                  f'Profesional: {profesionalservicio.profesional.nombre}\n' \
                  f'Servicio: {profesionalservicio.servicio.nombre}\n'
        from_email = 'arielmarchioni1@gmail.com'
        to_email = [user_email]
         # Crear una instancia de EmailMessage y enviar el correo electrónico
        email = EmailMessage(subject, message, from_email, to_email)
        email.send()

        # Enviar una copia del correo electrónico al remitente
        copy_subject = 'Confirmación de turno - Copia'
        copy_message = f'Tu turno ha sido confirmado exitosamente.\n\n' \
                       f'Fecha: {fecha.fecha}\n' \
                       f'Horario: {horario.horario}\n' \
                       f'Profesional: {profesionalservicio.profesional.nombre}\n' \
                       f'Servicio: {profesionalservicio.servicio.nombre}\n' \
                       f'Correo electrónico del usuario: {user_email}\n'

        copy_email = EmailMessage(copy_subject, copy_message, from_email, ['arielmarchioni1@gmail.com'])
        copy_email.send()    

        

        # Renderizar el template de turno confirmado con los datos del turno
        return render(request, 'turno_confirmado.html', {'turno': turno})

clinica/apps/turno/templates/confirmar_turno.html
{% extends 'base.html' %}

{% block title %}Confirmar turno{% endblock %}

{% block content %}
  <h1>Confirmar turno</h1>
  <p>Aquí puedes mostrar la información del turno seleccionado <br> y permitir al usuario confirmar la reserva.</p>
  
  <form method="POST" action="{% url 'turno:turno_confirmado' %}">
    {% csrf_token %}
    
    <p>Fecha: {{ fecha.fecha }}</p>
    <p>Horario: {{ horario.horario }}</p>
    <p>Profesional: {{ profesionalservicio.profesional.nombre }}</p>
    <p>Servicio: {{ profesionalservicio.servicio.nombre }}</p>
    
    <input type="hidden" name="fecha_id" value="{{ fecha.id }}">
    <input type="hidden" name="horario_id" value="{{ horario.id }}">
    <input type="hidden" name="profesionalservicio_id" value="{{ profesionalservicio.id }}">
    
    <button class="borrar" type="submit">Confirmar</button>
  </form>
{% endblock %}

clinica/apps/turno/templates/exito.html
<!-- exito.html -->
{% extends 'base.html' %}

{% block content %}
  <h1>Éxito</h1>
  <p>{{ mensaje }}</p>
{% endblock %}

clinica/apps/turno/templates/seleccionar_fecha.html
{% extends 'base.html' %}

{% block title %}Seleccionar fecha{% endblock %}

{% block content %}
  <h1>Seleccionar fecha</h1>
  <ul>
    {% for fecha in fechas %}
    <li><a href="{% url 'turno:seleccionar_horario' fecha_id=fecha.id profesionalservicio_id=profesionalservicio.id %}">{{ fecha.fecha }}</a></li>
    {% endfor %}
  
  </ul>
  {% if not fechas_generadas %}
    <a class="borrar" href="{% url 'turno:generar_fechas' %}">Generar Fechas</a>
  {% endif %}
{% endblock %}

clinica/apps/turno/templates/seleccionar_horario.html
{% extends 'base.html' %}

{% block title %}Seleccionar horario{% endblock %}

{% block content %}
  <h1>Seleccionar horario</h1>
  <h2>Fecha seleccionada: {{ fecha.fecha }}</h2>
  <ul>
    {% for horario in horarios %}
      <li>
        <form method="POST" action="{% url 'turno:confirmar_turno' fecha_id=fecha.id horario_id=horario.id profesionalservicio_id=profesionalservicio.id %}">
        
          {% csrf_token %}
          <input type="hidden" name="fecha_id" value="{{ fecha.id }}">
          <input type="hidden" name="horario_id" value="{{ horario.id }}">
          <input type="hidden" name="profesionalservicio_id" value="{{ profesionalservicio.id }}">
          <button class="borrar" type="submit">{{ horario.horario }}</button>
        </form>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

clinica/apps/turno/templates/turno_confirmado.html
{% extends 'base.html' %}

{% block title %}Turno Confirmado{% endblock %}

{% block content %}
  <h1>Turno Confirmado</h1>
  <p>Tu turno ha sido confirmado exitosamente.</p>
  <p>Fecha: {{ turno.fecha.fecha }}</p>
  <p>Horario: {{ turno.horario.horario }}</p>
  <p>Profesional: {{ turno.profesional_servicio.profesional.nombre }}</p>
  <p>Servicio: {{ turno.profesional_servicio.servicio.nombre }}</p>
{% endblock %}